/// <reference types="../global-types.ts" />

import './globals.css'

import type { Metadata } from 'next'

import { FONTS } from '../global/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type TProps = RequiredChildren

const RootLayout: React.FC<TProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={FONTS.poppins.className}>{children}</body>
    </html>
  )
}

export default RootLayout
